lazy val core = (project in file("core"))
lazy val query = (project in file("query"))
lazy val producer = (project in file("producer")).dependsOn(core)
lazy val spark = (project in file("spark")).dependsOn(core)
lazy val ripple = (project in file(".")).aggregate(core, query)